version: "3.7"

services:
  elasticsearch:
    container_name: elasticsearch_service
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    networks:
      docker-server:
        ipv4_address: 172.28.0.11
  # kibana:
  #   container_name: kibana_service
  #   image: docker.elastic.co/kibana/kibana:7.11.0
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://172.28.0.11:9200
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - 5601:5601
  #   networks:
  #     docker-server:
  #       ipv4_address: 172.28.0.12