version: "3.7"

services:
  mariadb:
    container_name: mariadb_service
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT_MYSQL}
    ports:
      - 3306:3306
    volumes:
      - '.docker/config/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf'
      - 'database-sync:/var/tmp/database'
    networks:
      docker-server:
        ipv4_address: 172.28.0.2