version: "3.7"

services:
  redis:
    container_name: redis_service
    image: redis
    ports:
      - 6379:6379
    networks:
      docker-server:
        ipv4_address: 172.28.0.5
  
  redis-commander:
    container_name: redis_commander_service
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      docker-server:
        ipv4_address: 172.28.0.6