version: "3.7"

services:
  web_service:
    container_name: web_service
    image: nginx:latest
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - php-fpm
    links:
      - php-fpm
    ports:
      - 80:80
      - 443:443
    volumes:
      - 'ssl-sync:/var/tmp/ssl'
      - 'source-sync:/var/www/html/source'
      - '.docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    networks:
      docker-server:
        ipv4_address: 172.28.0.10
